version: '3.8'
services:
  postgres:
    build: .
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: